### PR TITLE
Add multitech basics station guide

### PR DESCRIPTION
**Pull request by benolayinka**
Update multitech AEP guide to use LBS instead of ttn packet forwarder.

Still needs to be fixed for mLinux version.

### CODE REVIEW

**Comment by jpmeijers** [comment]
Have you tested this with TTN? Are you sure that the frequency plans match?

I have one of these gateways deployed, but the Multitech EU868 frequency plan does not match the TTN one, and therefore the gateway only receives data on 3 of the 8 channels.

**Review by johanstokking — APPROVED** [review]

**Comment by rvolosatovs** [comment]
> I have one of these gateways deployed, but the Multitech EU868 frequency plan does not match the TTN one, and therefore the gateway only receives data on 3 of the 8 channels.

I have exactly the same issue with my Conduit, perhaps we should add a frequency plan used by Multitech to https://github.com/TheThingsNetwork/lorawan-frequency-plans @johanstokking ?

**Comment by benolayinka** [comment]
> > I have one of these gateways deployed, but the Multitech EU868 frequency plan does not match the TTN one, and therefore the gateway only receives data on 3 of the 8 channels.
> 
> I have exactly the same issue with my Conduit, perhaps we should add a frequency plan used by Multitech to https://github.com/TheThingsNetwork/lorawan-frequency-plans @johanstokking ?

Ah that's an interesting solution..

**Review by laurensslats — APPROVED** [review]

**Comment by johanstokking** [comment]
> the Multitech EU868 frequency plan

Is this even a thing? Is this when selecting TTN as LNS?

I really don't care what gateway vendors think the best frequency plan is to use, but what I do know is that this is not a gateway (vendor) decision but an LNS one. We can't possibly create two worlds; one with MultiTech frequencies and one with TTN frequencies.

**Comment by benolayinka** [comment]
Updated to use LBS in firmware 5.30, should be released Oct 31

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
