### PR TITLE
Updated the screenshots, texts  with the new firmware

### PR DESCRIPTION
**Pull request by MarkNambatac**
- New Screenshots 
- Changed texts LoRa to LoRa® LoRaWAN to LoRaWAN™
Source: https://doc.rakwireless.com/rak2245-pi-hat-edition---lorawan----gateway-concentrator-module

### CODE REVIEW

**Review by johanstokking — CHANGES_REQUESTED** [review]
Afaik gateways are LoRa gateways, and there's nothing LoRaWAN specific.

As for the logo; LoRaWAN is (R), not (TM).

**Comment by MarkNambatac** [comment]
Hi @johanstokking. Thanks for the comment. According to this PDF (LoRa Alliance Marks & Logo Usage Policy and Guidelines, LoRaWAN should be LoRaWAN™. Please see the attached pdf below
image

[2_share_file.pdf](https://github.com/TheThingsNetwork/docs/files/4265713/2_share_file.pdf)

**Comment by johanstokking** [comment]
You would assume (and hope) that at least the LoRa Alliance uses the right mark on their own website? https://lora-alliance.org/about-lorawan

Where does your document come from?

It's from September 2018, and I think the Alliance was in the midst of changing (TM) to (R)/(CM), or the other way around.

@laurensslats probably knows the answer

**Comment by MarkNambatac** [comment]
> You would assume (and hope) that at least the LoRa Alliance uses the right mark on their own website? https://lora-alliance.org/about-lorawan
> 
> Where does your document come from?
> 
> It's from September 2018, and I think the Alliance was in the midst of changing (TM) to (R)/(CM), or the other way around.
> 
> @laurensslats probably knows the answer

Will wait for the response of @laurensslats

**Comment by laurensslats** [comment]
It's LoRaWAN(R) (not TM). @MarkNambatac please update so I can merge the PR.

**Comment by laurensslats** [comment]
@MarkNambatac can you do the final edits so I can merge?

**Comment by johanstokking** [comment]
Also reword the commit messages to align with our guidelines (need subject, need verb in imperative tense).

@laurensslats you can try checking out the branch from their remote and reword and fixup yourself.

**Comment by benolayinka** [comment]
@MarkNambatac i couldn't push to your master or make a new branch in your repo, so I moved your PR here with corrections: https://github.com/TheThingsNetwork/docs/pull/404/commits

**Pull request closed without merging**
