### PR TITLE
Move docs to hugo

### PR DESCRIPTION
**Pull request by benolayinka**
Replaced by https://github.com/TheThingsNetwork/docs/pull/441

This PR migrates the current TTN.org/learn section to Hugo, with the following content sections from the ttn.org restructuring:

- Applications
- Devices
- LoraWAN
- V2 Docs
- Quick Start

Subsections of LoRaWAN will be:
- Glossary
- LoRaWAN specifications
- LoRaWAN fundamentals

Currently looks like this:

Bildschirmfoto 2021-03-22 um 17 48 05
Bildschirmfoto 2021-03-22 um 17 48 43

### CODE REVIEW

**Comment by nejraselimovic** [comment]
If I run `make server` I get this:

error

Running `make init` gives me the same error as @laurensslats has. 

@benolayinka How do we run this?

**Comment by nejraselimovic** [comment]
> If I run `make server` I get this:
> 
> error
> 
> Running `make init` gives me the same error as @laurensslats has.
> 
> @benolayinka How do we run this?

It's good now, I can run it, and it's way easier than what we have now. Things that I think should be done before merging this: 

- discuss landing page organization (rearrange page cards)
- upgrade design & visuals (match design with tti.com?, new icons)
- fix broken references
- discuss navigation through docs

**Review by nejraselimovic — APPROVED** [review]

**Comment by nejraselimovic** [comment]
Screenshot from 2021-03-23 15-15-46

@benolayinka shouldn't titles from these cards be shown in the menu on the left side? No one is expecting to find them on the bottom of the page. Other than that, I think this looks good

**Comment by benolayinka** [comment]
Replaced by https://github.com/TheThingsNetwork/docs/pull/441

**Pull request closed without merging**
