### PR TITLE
java sdk for 2.0.0

### PR DESCRIPTION
**Pull request by cambierr**
We should probably also publish the javadoc somewhere as this is the main doc source used by java devs

### CODE REVIEW

**Comment by FokkeZB** [comment]
We'll have to wait for Maven to have Travis pass: https://travis-ci.org/TheThingsNetwork/docs/builds/184238501 😉

**Comment by FokkeZB** [comment]
Yes, we should indeed put the javadoc up. I suggest to put it in the docs folder of the repo and configure to serve that via GitHub Pages

**Comment by cambierr** [comment]
Can't we do something similar to the api.md files ? it would probably be much easier ;)

**Comment by cambierr** [comment]
I updated the artifact links from maven central to the github repo since it's probably more pertinent as source of information for them.

**Comment by FokkeZB** [comment]
@cambierr could you also include the pulled in `api.md`? Just run `npm run pull`. Because when I merge it immediately publishes.

**Comment by FokkeZB** [comment]
As for javadoc, it's a bunch of HTML and css right? I rather keep that outside the docs, with the repo. And since GitHub Pages can serve from a `/docs` subdir, that sounds ideal to me?

**Comment by cambierr** [comment]
temp api.md was added

**Comment by cambierr** [comment]
I suggest we deal with javadoc once all v2 components will be ready ;-)

**Review by FokkeZB — CHANGES_REQUESTED** [review]
The front matter is missing in `api.md`. If you pull it in via `npm run pull` it should add it for you.

**Comment by FokkeZB** [comment]
Replaced by #109

**Pull request closed without merging**
