### PR TITLE
Updated for production console

### PR DESCRIPTION
**Pull request by spidie**

### CODE REVIEW

**Review by FokkeZB — CHANGES_REQUESTED** [review]
Thanks for spotting this, but could you instead change the link to ../registration.md ?

**Comment by spidie** [comment]
Do you mean changing this page from register.md -> registration.md? Or something else.

**Comment by FokkeZB** [comment]
No, I mean the link you changed in this PR; change it to `../registration.md` so that it will link to https://www.thethingsnetwork.org/docs/gateways/registration.html (https://github.com/thethingsnetwork/docs/blob/master/_content/gateways/registration.md)

**Comment by spidie** [comment]
got it.

**Pull request closed without merging**
