### PR TITLE
update Kerlink documentation

### PR DESCRIPTION
**Pull request by BenoitDuffez**
Wirnet Station is now a legacy product
Added new products (iFemto-Evo and iStation)
Updated docs to have up to date information
Fixed a bit the formatting
Streamlined all the documentation in a single page since
the firmware is unified and so is the packet forwarder

### CODE REVIEW

**Comment by BenoitDuffez** [comment]
I added my work email to my profile & signed the CLA but apparently it's still not happy. Is there anything I can do to help merge this?

**Comment by johanstokking** [comment]
@BenoitDuffez the problem is that your commit email address is different from the one with which you signed.

Can you change the author email address of your commit per https://makandracards.com/makandra/1717-git-change-author-of-a-commit ?

**Comment by BenoitDuffez** [comment]
I thought having the email verified in my profile would be enough. I amended the commit author.

**Review by laurensslats — APPROVED** [review]

**Comment by johanstokking** [comment]
@laurensslats this commit message is also not following the guidelines. This should not have been merged.

**Pull request merged**
