### PR TITLE
Added RAK2245 Pi Hat Documentation

### PR DESCRIPTION
**Pull request by MarkNambatac**
Added the RAK2245 Pi Hat in the list of gateways

### CODE REVIEW

**Comment by MarkNambatac** [comment]
How can i resolve this issue?

**Comment by johanstokking** [comment]
Hi @MarkNambatac, thanks for your contribution.

Can you try without updating the dependences?

**Comment by MarkNambatac** [comment]
> Hi @MarkNambatac, thanks for your contribution.
> 
> Can you try without updating the dependences?
Hi @johanstokking. I have to update the dependencies first for it to work. If I won't update it using `bundle update` command  I get this error:
image

**Comment by MarkNambatac** [comment]
Any updates on this?

**Comment by johanstokking** [comment]
@MarkNambatac please reopen. We're getting #319 in first and update deps there.

**Comment by MarkNambatac** [comment]
No problem. I created another pull request. I think that would be fine. Any chance that it will be merged ?

**Comment by johanstokking** [comment]
Sure, we have a bunch of open PRs here that we'll be accepting.

It's just that we can't accept dependency updates as part of content contributions for now; let us figure that out first so you can focus on content. Apologies for the inconvenience that caused.

**Pull request closed without merging**
