### PR TITLE
Add Spread-Spectrum paragraph

### PR DESCRIPTION
**Pull request by dicktonyboy**
Spread spectrum security paragraph added

### CODE REVIEW

**Comment by johanstokking** [comment]
Thanks!

Can you sign the CLA and resolve the TODO?

**Comment by dicktonyboy** [comment]
is that okay?

**Comment by johanstokking** [comment]
Yes, but there's still a TODO in the text!

**Comment by egourlao** [comment]
@dicktonyboy I've updated your pull request here https://github.com/TheThingsNetwork/docs/pull/225/commits/ac24a570424771eb9e3dc9855e68982887995b57 to remove the TODO from the text.

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
