### PR TITLE
Reverse SSH tunnel for Kerlink

### PR DESCRIPTION
**Pull request by jpmeijers**
Document how to create a reverse SSH tunnel from a Kerlink gateway and dial it at system startup.

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]

**Comment by nejraselimovic** [comment]
@jpmeijers is this still relevant? For V3 documentation I mean.

**Comment by jpmeijers** [comment]
Yes I believe this is still useful. A reverse ssh tunnel provides remote access to the gateway. Alternatives are OpenVPN and perhaps a the CUPS when BasicStation is used.

**Comment by johanstokking** [comment]
@jpmeijers thanks. Does this PR need any updates or can it be merged as is?

**Comment by jpmeijers** [comment]
I just scanned through the document, and it all still looks valid to me. It's a very generic reverse ssh setup, which will likely work on any Linux-based gateway.

**Comment by johanstokking** [comment]
Thanks!

Dankie!

**Pull request merged**
